In [3]:
from pathlib import Path
import pandas as pd

In [4]:
BASE_DIR = Path.cwd().parent

In [5]:
DATA_DIR = BASE_DIR / "data"

In [7]:
bonds = pd.read_csv(DATA_DIR/"bond_portfolio_data.csv")
yield_curve = pd.read_csv(DATA_DIR/"yield_curve_history.csv")
mc = pd.read_csv(DATA_DIR/"monte_carlo_scenarios.csv")

In [8]:
print(bonds.shape)
print(yield_curve.shape)
print(mc.shape)

(300, 44)
(264, 8)
(1000, 9)

In [9]:
bonds.head()

,BondID,ISIN,Issuer,Sector,CreditRating,Currency,FaceValue,CouponRate,CouponFrequency,BondType,...,CallDate,IsPutable,IsFloatingRate,BenchmarkIndex,PriceChange_Up50bps,PriceChange_Dn50bps,PriceChange_Up100bps,PriceChange_Dn100bps,PriceChange_Up200bps,PriceChange_Dn200bps
0,ZTFI-0001,IN1043321819,Government of India,Government,SOV,INR,100,0.0620,2,Fixed,...,NaN,False,False,IN10YT,0.9207,-0.9098,1.8522,-1.8086,3.7480,-3.5736
1,ZTFI-0002,IN7940265423,Government of India,Government,SOV,INR,100,0.0773,2,Fixed,...,NaN,False,False,IN10YT,6.1042,-5.6378,12.6747,-10.8091,27.2150,-19.7526
2,ZTFI-0003,IN7816184959,Government of India,Government,SOV,INR,100,0.0555,2,Fixed,...,NaN,False,False,IN10YT,2.0557,-2.0040,4.1631,-3.9562,8.5332,-7.7056
3,ZTFI-0004,IN4752553419,Government of India,Government,SOV,INR,100,0.0681,2,Fixed,...,NaN,False,False,IN10YT,6.3440,-5.7961,13.2358,-11.0444,28.6631,-19.8973
4,ZTFI-0005,IN5030564139,Government of India,Government,SOV,INR,100,0.0750,2,Fixed,...,NaN,False,False,IN10YT,5.4267,-5.0533,11.2267,-9.7333,23.9468,-17.9731

In [10]:
bonds.info()
bonds.isnull().sum()
bonds.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 44 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   BondID                   300 non-null    object
 1   ISIN                     300 non-null    object
 2   Issuer                   300 non-null    object
 3   Sector                   300 non-null    object
 4   CreditRating             300 non-null    object
 5   Currency                 300 non-null    object
 6   FaceValue                300 non-null    int64
 7   CouponRate               300 non-null    float64
 8   CouponFrequency          300 non-null    int64
 9   BondType                 300 non-null    object
 10  IssueDate                300 non-null    object
 11  MaturityDate             300 non-null    object
 12  ValuationDate            300 non-null    object
 13  YearsToMaturity          300 non-null    float64
 14  OriginalMaturityYears    300 non-null    int64
 15  YieldToMaturity          300 non-null    float64
 16  CleanPrice               300 non-null    float64
 17  AccruedInterest          300 non-null    float64
 18  DirtyPrice               300 non-null    float64
 19  MacaulayDuration         300 non-null    float64
 20  ModifiedDuration         300 non-null    float64
 21  Convexity                300 non-null    float64
 22  DV01_Per100Face          300 non-null    float64
 23  EffectiveDuration        300 non-null    float64
 24  EffectiveConvexity       300 non-null    float64
 25  SpreadOverBenchmark_bps  300 non-null    int64
 26  OAS_bps                  300 non-null    int64
 27  ZSpread_bps              300 non-null    int64
 28  KeyRateBucket            300 non-null    object
 29  Quantity                 300 non-null    int64
 30  MarketValue_LocalCcy     300 non-null    float64
 31  MarketValue_INR          300 non-null    float64
 32  PortfolioWeight          300 non-null    float64
 33  IsCallable               300 non-null    bool
 34  CallDate                 17 non-null     object
 35  IsPutable                300 non-null    bool
 36  IsFloatingRate           300 non-null    bool
 37  BenchmarkIndex           300 non-null    object
 38  PriceChange_Up50bps      300 non-null    float64
 39  PriceChange_Dn50bps      300 non-null    float64
 40  PriceChange_Up100bps     300 non-null    float64
 41  PriceChange_Dn100bps     300 non-null    float64
 42  PriceChange_Up200bps     300 non-null    float64
 43  PriceChange_Dn200bps     300 non-null    float64
dtypes: bool(3), float64(21), int64(7), object(13)
memory usage: 97.1+ KB

,FaceValue,CouponRate,CouponFrequency,YearsToMaturity,OriginalMaturityYears,YieldToMaturity,CleanPrice,AccruedInterest,DirtyPrice,MacaulayDuration,...,Quantity,MarketValue_LocalCcy,MarketValue_INR,PortfolioWeight,PriceChange_Up50bps,PriceChange_Dn50bps,PriceChange_Up100bps,PriceChange_Dn100bps,PriceChange_Up200bps,PriceChange_Dn200bps
count,300.0,300.000000,300.0,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,...,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000
mean,100.0,0.064048,2.0,7.497240,12.220000,0.068797,97.059941,0.824847,97.827460,5.068667,...,85120.666667,83641.256800,106864.486567,0.003333,2.381898,-2.249665,4.896032,-4.367098,10.320994,-8.205265
std,0.0,0.026788,0.0,8.167838,9.912574,0.023282,6.115074,0.608935,6.309559,4.488809,...,140244.290947,137915.643134,146395.828670,0.004566,2.080866,1.889739,4.354404,3.590223,9.484457,6.433185
min,100.0,0.002300,2.0,0.517500,2.000000,0.007900,70.163200,0.003000,70.191900,0.500000,...,50.000000,37.330000,27.070000,0.000001,0.236000,-9.269900,0.473100,-17.350700,0.950700,-30.192900
25%,100.0,0.043550,2.0,1.980125,4.000000,0.047000,95.185250,0.312800,95.865025,1.464525,...,5000.000000,4586.297500,9885.557500,0.000308,0.724175,-3.519750,1.455300,-6.871225,2.938500,-13.059700
50%,100.0,0.070250,2.0,3.715250,8.000000,0.073100,99.075000,0.683700,99.785800,3.142000,...,20000.000000,19386.240000,48924.150000,0.001526,1.535300,-1.507050,3.098750,-2.985850,6.310450,-5.858850
75%,100.0,0.082025,2.0,10.061600,19.000000,0.083775,100.365775,1.305625,101.432925,7.609800,...,100000.000000,99341.800000,143977.735000,0.004491,3.688000,-0.717150,7.544150,-1.427350,15.743150,-2.826750
max,100.0,0.115100,2.0,38.899400,40.000000,0.119000,109.134700,2.704100,110.301400,22.399900,...,500000.000000,519069.500000,523964.380000,0.016344,10.458800,-0.234900,22.106600,-0.468700,48.969000,-0.932900